language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
      addons:
        postgresql: "9.3"
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli

    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
      addons:
        postgresql: "9.3"
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
      addons:
        postgresql: "9.3"
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
      addons:
        postgresql: "9.3"
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
      addons:
        postgresql: "9.4"
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli

    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
      addons:
        postgresql: "9.3"
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
      addons:
        postgresql: "9.3"
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
      addons:
        postgresql: "9.4"
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - export TRAVIS_BUILD_DIR="/home/travis/build/talis/aspire-moodle-integration/2.x-activity-module/mod/aspirelists"
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  #- moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  #- moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  #- moodle-plugin-ci behat
